### ISSUE TITLE
Protect Editing killing login modal in Shady DOM 

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-admin#15]
If not using Shadow DOM, looks like `simpla-admin` is somehow blocking both the clicks to the `login` button and also form submits (not sure how that one's happening).

Needs further investigating, but should be fixed ASAP given it essentially stops `simpla-admin` working in Shady.

**Comment by madeleineostoja** [comment]
I think we should fix this by exposing a general attribute/prop that simpla-admin skips over when  disabling pointer events - same use-case as any custom user edit UI (in this case the 'custom' edit UI I'd the admin modal), no way to make it clickable with protectEditing

**Comment by madeleineostoja** [comment]
Though of course simpla-admin shouldn't touch its own DOM regardless, so this is kind of a separate issue.

**Comment by madeleineostoja** [comment]
Looks like this was fixed in https://github.com/SimplaElements/simpla-admin/commit/04890acc8a4b11249ed49c1c2be26a807509528f, but I'd like to use cleaner logic.

In any case will open a new issue for earmarking elements to be ignored by edit protection
