### ISSUE TITLE
Disable pointer events while editable

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-admin#2]
Simpla admin should kill pointer events on all non-Simpla elements while in edit mode. This makes editing with Simpla more robust and less frustration-prone. Then to click on a link, the user can just quickly toggle edit mode off then back on.

We did have a tree-walker around for this, but it's long gone. Will need input from @bedeoverend on best implementation. Business logic would be to disable pointer events on all elements that don't match the following regex:

```js
/^simpla-/.test(el.tagName)
```

This should also be configurable once #1 is implemented

**Comment by bedeoverend** [comment]
I believe you also need to _not_ touch any element that _contains_ a simpla element. That's why the walker was there I believe. I believe that how disabling pointer events works. Still poses the problem of: `<a href="https://google.com"><simpla-text sid="test">...</simpla-text></a>` to edit `simpla-text` by clicking on it, you'd need to have pointer events enabled on it and it's ancestors, but that means you could click on the link...might also need to prevent default actions when clicking on `simpla-*` elements.

**Comment by madeleineostoja** [comment]
Hrmm.. yeah will have to do some testing. The trouble is that this needs to be a generic as possible solution, not just for simpla-text etc.

Maybe we just intercept anchor clicks with preventdefault, and if devs are doing imperitive click stuff they can nuke in edit mode themselves?

**Comment by bedeoverend** [comment]
Yeah I'd say clicks on our elements automatically hijack the click to stop things like this. But - that sounds like it should be the responsibility of each individual element, as it may differ from each element depending on how they respond to clicks.

**Comment by madeleineostoja** [comment]
No I was meaning that admin or the SDK intercepts all anchors on the page, similar to how app-route hooks into anchor clicks, and then exposes an event for imprleritive route changes.

This should definitely be something simpla-admin or the SDK handles, not an element-by-element thing

**Comment by bedeoverend** [comment]
Hmm...this does leave out cases if a user uses non-standard things to open a modal or some such e.g. click an image to open a gallery, what if they don't use a link? I'm not sure how common it is to use non-links in those scenarios.

**Comment by madeleineostoja** [comment]
Pretty common, but I think it's fair enough to ask them to do something themselves in that case - eg: expose an event/method on simpla-admin to disable a given action while simpla is in edit mode.

I mean ideally we could use pointer events and it'd work across the board, but sounds like that's not the case? For a generalised, non-element-specific system that is.

**Comment by madeleineostoja** [comment]
Also not sure if this should live in simpla-admin or the SDK?

**Comment by madeleineostoja** [comment]
Bump @bedeoverend.

Makes edit mode feel broken at the moment, think this needs to be implemented sooner rather than later. We've had lots of comments in the past about the need for this too.

**Comment by bedeoverend** [comment]
Yeah I'd like to get out the SDK first, though it certainly is a priority, people do need it. Definitely think it should live in admin, that's where all our other UI stuff goes.

It'll take some experimentation, I'm still not sure of how to do this properly. I think ultimately we'll have to try tackle the majority use case and then give options for users to handle edge cases.

**Comment by bedeoverend** [comment]
Thinking back, I believe the tree walker we had was actually to change the opacity of trees that didn't have nested Simpla Elements. Meaning that it would show what things were editable and what weren't. We couldn't use the same walker as it would only disable elements that have no nested Simpla Elements - which wouldn't achieve what we want. What we want is for clicks on Simpla Elements to not affected it's parent DOM. 

I'd say stopping clicks from bubbling from Simpla Elements is probably the best thing to do here.
