### ISSUE TITLE
simpla-login import flaky on Chrome

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-admin#3]
The dynamic import for `simpla-login` (and only `simpla-login`) intermittently blows up with native HTML imports in Chrome. 

The import is injected into the head properly, and the resources are fetched, but the element doesn't upgrade, and if you don't have `async` on all other dynamic imports, they all blow up. 

Only happens with `simpla-login`.

Task for @bedeoverend to have fun with methinks. If it's not a straightforward fix, we can just import simpla-login declaratively for now, even hacking perf by just throwing it inside `simpla-admin-controls.html` for now.

**Comment by bedeoverend** [comment]
> Task for @bedeoverend to have fun with methinks
Joy 😛 

But yeah - agree, I've had some nasty experience with imports in the past, for example see [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=669710&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=). I think imports is a bit buggy in general, but they're not gonna dedicate many resources to it given the lack of support across the vendors I'd say.

**Comment by madeleineostoja** [comment]
Yep I'd say if can't find a quick fix (or if it doesn't fix itself - haven't noticed it lately tbh) then just throw the login import into the editor component and call it done. Dirty hack, and a perf hit, but it's only when edtliting so I can live with that for now.

**Comment by madeleineostoja** [comment]
This seems to have resolved itself, closing for now
